server:
  port: 6003

spring:
  profiles:
    active: dev
  application:
    name: api-user
#注册eureka服务
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}

