server:
  port: 6001
eureka:
  client:
    #    禁止自己注册自己
    register-with-eureka: true
    #    屏蔽注册信息
    fetch-registry: true
    #    服务注册中心实例的主机名
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
spring:
  application:
    name: eurka_service