server:
  port: 7002
#pring相关配置
spring:
  profiles:
#    使用哪个配置文件
    active: dev
  application:
    name: application-data
  jackson:
    time-zone: GMT+8
  cloud:
    alibaba:
      seata:
        tx-service-group: zj_tx_group #自定义事务组名称需要与seata-server中的对应
#注册eureka服务
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
#服务超时配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
#超时配置
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
mybatis:
  mapperLocations: classpath:mapper/*.xml


