#spring相关配置
spring:
  datasource:
    # master数据源配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zj_data?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
#注册eureka服务
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 6
